# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu:latest

build:
  stage: build
  before_script:
   - apt update && apt install -y g++ git cmake 
  script:
    - cd build && cmake -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS}
  artifacts:
    paths:
      - build


# run tests using the binary built before
test:
  stage: test
  dependencies:
    - build
  script:
    - cd build
    - rm CMakeCache.txt
    - cd build && cmake -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS}
    - ctest
