image: ubuntu:latest
before_script:
  - apt-get update
  - TZ="Canada/Montreal" DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends tzdata
  - apt install -y --no-install-recommends build-essential cmake
build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build


# run tests using the binary built before
test:
  stage: test
  dependencies:
    - build
  script:
    - ctest
  artifacts:
    paths:
      - build

