image: ubuntu:latest
before_script:
  - apt-get update
  - TZ="Canada/Montreal" DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends tzdata
  - apt-get install -y --no-install-recommends build-essential cmake libgmp-dev libboost-all-dev ocl-icd-opencl-dev libtbb-dev libbenchmark-dev
build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
  artifacts:
    paths:
      - build


# run tests using the binary built before
test:
  stage: test
  dependencies:
    - build
  script:
 #   - cd build
 #   - make
    - ctest
  artifacts:
    paths:
      - build

